apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ChamBit-InNodeAgent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: ChamBit-InNodeAgent
  template:
    metadata:
      labels:
        app: ChamBit-InNodeAgent
    spec:
      hostPID: true
      containers:
      - name: ChamBit-InNodeAgent
        image: yourrepo/ChamBit-InNodeAgent:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: bpf
          mountPath: /sys/fs/bpf
        - name: modules
          mountPath: /lib/modules
        - name: debugfs
          mountPath: /sys/kernel/debug
        - name: log
          mountPath: /host/var/log
      volumes:
      - name: bpf
        hostPath:
          path: /sys/fs/bpf
      - name: modules
        hostPath:
          path: /lib/modules
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      - name: log
        hostPath:
          path: /var/log
